apiVersion: apps/v1
kind: Deployment
metadata:
  name: productbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productbackend
  template:
    metadata:
      labels:
        app: productbackend
    spec:
      containers:
      - name: productbackend
        image: YOUR_ECR_REPOSITORY/productbackend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: productbackend
spec:
  selector:
    app: productbackend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
