apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-springboot
  template:
    metadata:
      labels:
        app: backend-springboot
    spec:
      containers:
      - name: backend-springboot
        image: YOUR_ECR_REPOSITORY/backend-springboot:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-springboot
spec:
  selector:
    app: backend-springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
