AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy services to ECS'

Parameters:
  VPC_ID:
    Type: String
  PUBLIC_SUBNET_1:
    Type: String
  PUBLIC_SUBNET_2:
    Type: String
  ALB_LISTENER_ARN:
    Type: String
  ECS_SERVICE_SECURITY_GROUP:
    Type: String
  CLUSTER_NAME:
    Type: String
    Default: my-ecs-cluster
  ECR_BASE_URL:
    Type: String
  ACCOUNTID:
    Type: String

Resources:
  # --- Eureka Server ---
  EurekaTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: eurekaserver-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${ACCOUNTID}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: eurekaserver
          Image: !Sub "${ECR_BASE_URL}/eurekaserver:latest"
          PortMappings: [{ ContainerPort: 8761 }]

  EurekaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: eurekaserver-tg
      VpcId: !Ref VPC_ID
      Protocol: HTTP
      Port: 8761
      HealthCheckPath: /
      TargetType: ip

  EurekaListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALB_LISTENER_ARN
      Priority: 1
      Actions: [{ Type: forward, TargetGroupArn: !Ref EurekaTargetGroup }]
      Conditions: [{ Field: path-pattern, Values: [/eureka/*] }]

  EurekaService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: eurekaserver-service
      Cluster: !Ref CLUSTER_NAME
      TaskDefinition: !Ref EurekaTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref PUBLIC_SUBNET_1, !Ref PUBLIC_SUBNET_2]
          SecurityGroups: [!Ref ECS_SERVICE_SECURITY_GROUP]
      LoadBalancers:
        - TargetGroupArn: !Ref EurekaTargetGroup
          ContainerName: eurekaserver
          ContainerPort: 8761

  # --- Backend Spring Boot ---
  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: backend-springboot-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${ACCOUNTID}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: backend-springboot
          Image: !Sub "${ECR_BASE_URL}/backend-springboot:latest"
          PortMappings: [{ ContainerPort: 8080 }]
          Environment: [{ Name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE, Value: "http://eurekaserver-service.local:8761/eureka" }]

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: backend-springboot-tg
      VpcId: !Ref VPC_ID
      Protocol: HTTP
      Port: 8080
      HealthCheckPath: /actuator/health
      TargetType: ip

  BackendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALB_LISTENER_ARN
      Priority: 2
      Actions: [{ Type: forward, TargetGroupArn: !Ref BackendTargetGroup }]
      Conditions: [{ Field: path-pattern, Values: [/api/employees/*] }]

  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: backend-springboot-service
      Cluster: !Ref CLUSTER_NAME
      TaskDefinition: !Ref BackendTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref PUBLIC_SUBNET_1, !Ref PUBLIC_SUBNET_2]
          SecurityGroups: [!Ref ECS_SERVICE_SECURITY_GROUP]
      LoadBalancers:
        - TargetGroupArn: !Ref BackendTargetGroup
          ContainerName: backend-springboot
          ContainerPort: 8080
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !Ref CLUSTER_NAME

  # --- Product Backend ---
  ProductTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: productbackend-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${ACCOUNTID}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: productbackend
          Image: !Sub "${ECR_BASE_URL}/productbackend:latest"
          PortMappings: [{ ContainerPort: 8080 }]
          Environment: [{ Name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE, Value: "http://eurekaserver-service.local:8761/eureka" }]

  ProductTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: productbackend-tg
      VpcId: !Ref VPC_ID
      Protocol: HTTP
      Port: 8080
      HealthCheckPath: /actuator/health
      TargetType: ip

  ProductListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALB_LISTENER_ARN
      Priority: 3
      Actions: [{ Type: forward, TargetGroupArn: !Ref ProductTargetGroup }]
      Conditions: [{ Field: path-pattern, Values: [/api/products/*] }]

  ProductService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: productbackend-service
      Cluster: !Ref CLUSTER_NAME
      TaskDefinition: !Ref ProductTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref PUBLIC_SUBNET_1, !Ref PUBLIC_SUBNET_2]
          SecurityGroups: [!Ref ECS_SERVICE_SECURITY_GROUP]
      LoadBalancers:
        - TargetGroupArn: !Ref ProductTargetGroup
          ContainerName: productbackend
          ContainerPort: 8080
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !Ref CLUSTER_NAME

  # --- Inventory Backend ---
  InventoryTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: inventorybackend-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${ACCOUNTID}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: inventorybackend
          Image: !Sub "${ECR_BASE_URL}/inventorybackend:latest"
          PortMappings: [{ ContainerPort: 8080 }]
          Environment: [{ Name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE, Value: "http://eurekaserver-service.local:8761/eureka" }]

  InventoryTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: inventorybackend-tg
      VpcId: !Ref VPC_ID
      Protocol: HTTP
      Port: 8080
      HealthCheckPath: /actuator/health
      TargetType: ip

  InventoryListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALB_LISTENER_ARN
      Priority: 4
      Actions: [{ Type: forward, TargetGroupArn: !Ref InventoryTargetGroup }]
      Conditions: [{ Field: path-pattern, Values: [/api/inventory/*] }]

  InventoryService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: inventorybackend-service
      Cluster: !Ref CLUSTER_NAME
      TaskDefinition: !Ref InventoryTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref PUBLIC_SUBNET_1, !Ref PUBLIC_SUBNET_2]
          SecurityGroups: [!Ref ECS_SERVICE_SECURITY_GROUP]
      LoadBalancers:
        - TargetGroupArn: !Ref InventoryTargetGroup
          ContainerName: inventorybackend
          ContainerPort: 8080
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !Ref CLUSTER_NAME

  # --- Order Backend ---
  OrderTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: orderbackend-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${ACCOUNTID}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: orderbackend
          Image: !Sub "${ECR_BASE_URL}/orderbackend:latest"
          PortMappings: [{ ContainerPort: 8080 }]
          Environment: [{ Name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE, Value: "http://eurekaserver-service.local:8761/eureka" }]

  OrderTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: orderbackend-tg
      VpcId: !Ref VPC_ID
      Protocol: HTTP
      Port: 8080
      HealthCheckPath: /actuator/health
      TargetType: ip

  OrderListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALB_LISTENER_ARN
      Priority: 5
      Actions: [{ Type: forward, TargetGroupArn: !Ref OrderTargetGroup }]
      Conditions: [{ Field: path-pattern, Values: [/api/orders/*] }]

  OrderService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: orderbackend-service
      Cluster: !Ref CLUSTER_NAME
      TaskDefinition: !Ref OrderTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref PUBLIC_SUBNET_1, !Ref PUBLIC_SUBNET_2]
          SecurityGroups: [!Ref ECS_SERVICE_SECURITY_GROUP]
      LoadBalancers:
        - TargetGroupArn: !Ref OrderTargetGroup
          ContainerName: orderbackend
          ContainerPort: 8080
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !Ref CLUSTER_NAME

  # --- Frontend Angular ---
  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: frontend-angular-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${ACCOUNTID}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: frontend-angular
          Image: !Sub "${ECR_BASE_URL}/employee-frontend:latest"
          PortMappings: [{ ContainerPort: 80 }]

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: frontend-angular-tg
      VpcId: !Ref VPC_ID
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /
      TargetType: ip

  FrontendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALB_LISTENER_ARN
      Priority: 10
      Actions: [{ Type: forward, TargetGroupArn: !Ref FrontendTargetGroup }]
      Conditions: [{ Field: path-pattern, Values: [/*] }]

  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: frontend-angular-service
      Cluster: !Ref CLUSTER_NAME
      TaskDefinition: !Ref FrontendTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref PUBLIC_SUBNET_1, !Ref PUBLIC_SUBNET_2]
          SecurityGroups: [!Ref ECS_SERVICE_SECURITY_GROUP]
      LoadBalancers:
        - TargetGroupArn: !Ref FrontendTargetGroup
          ContainerName: frontend-angular
          ContainerPort: 80
